## The Subscription Seer

#### Setup or Importing Libraries

In [1]:
import tensorflow as tf
import keras
from keras.utils import FeatureSpace
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

#### Load the Data

In [3]:
df = pd.read_csv('bank.csv')

## DF properties

#### Preview

In [4]:
df.head()

Unnamed: 0  age          job  marital          education default  housing  \
0           0   30  blue-collar  married           basic.9y      no      yes   
1           1   39     services   single        high.school      no       no   
2           2   25     services  married        high.school      no      yes   
3           3   38     services  married           basic.9y      no  unknown   
4           4   47       admin.  married  university.degree      no      yes   

      loan    contact month  ... campaign  pdays  previous     poutcome  \
0       no   cellular   may  ...        2    999         0  nonexistent   
1       no  telephone   may  ...        4    999         0  nonexistent   
2       no  telephone   jun  ...        1    999         0  nonexistent   
3  unknown  telephone   jun  ...        3    999         0  nonexistent   
4       no   cellular   nov  ...        1    999         0  nonexistent   

   emp.var.rate cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          -1.8         92.893          -46.2      1.313       5099.1  no  
1           1.1         93.994          -36.4      4.855       5191.0  no  
2           1.4         94.465          -41.8      4.962       5228.1  no  
3           1.4         94.465          -41.8      4.959       5228.1  no  
4          -0.1         93.200          -42.0      4.191       5195.8  no  

[5 rows x 22 columns]

#### Shape

In [5]:
df.shape

(4119, 22)

#### Columns

In [6]:
df.columns

Index(['Unnamed: 0', 'age', 'job', 'marital', 'education', 'default',
       'housing', 'loan', 'contact', 'month', 'day_of_week', 'duration',
       'campaign', 'pdays', 'previous', 'poutcome', 'emp.var.rate',
       'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

#### Info

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4119 entries, 0 to 4118
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Unnamed: 0      4119 non-null   int64  
 1   age             4119 non-null   int64  
 2   job             4119 non-null   object 
 3   marital         4119 non-null   object 
 4   education       4119 non-null   object 
 5   default         4119 non-null   object 
 6   housing         4119 non-null   object 
 7   loan            4119 non-null   object 
 8   contact         4119 non-null   object 
 9   month           4119 non-null   object 
 10  day_of_week     4119 non-null   object 
 11  duration        4119 non-null   int64  
 12  campaign        4119 non-null   int64  
 13  pdays           4119 non-null   int64  
 14  previous        4119 non-null   int64  
 15  poutcome        4119 non-null   object 
 16  emp.var.rate    4119 non-null   float64
 17  cons.price.idx  4119 non-null   f

#### Correlation

In [8]:
df.corr(numeric_only=True)

Unnamed: 0       age  duration  campaign     pdays  previous  \
Unnamed: 0        1.000000  0.030971  0.012072 -0.000211  0.000781 -0.008499   
age               0.030971  1.000000  0.041299 -0.014169 -0.043425  0.050931   
duration          0.012072  0.041299  1.000000 -0.085348 -0.046998  0.025724   
campaign         -0.000211 -0.014169 -0.085348  1.000000  0.058742 -0.091490   
pdays             0.000781 -0.043425 -0.046998  0.058742  1.000000 -0.587941   
previous         -0.008499  0.050931  0.025724 -0.091490 -0.587941  1.000000   
emp.var.rate     -0.017758 -0.019192 -0.028848  0.176079  0.270684 -0.415238   
cons.price.idx   -0.033435 -0.000482  0.016672  0.145021  0.058472 -0.164922   
cons.conf.idx     0.031584  0.098135 -0.034745  0.007882 -0.092090 -0.051420   
euribor3m        -0.003764 -0.015033 -0.032329  0.159435  0.301478 -0.458851   
nr.employed       0.003782 -0.041936 -0.044218  0.161037  0.381983 -0.514853   

                emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
Unnamed: 0         -0.017758       -0.033435       0.031584  -0.003764   
age                -0.019192       -0.000482       0.098135  -0.015033   
duration           -0.028848        0.016672      -0.034745  -0.032329   
campaign            0.176079        0.145021       0.007882   0.159435   
pdays               0.270684        0.058472      -0.092090   0.301478   
previous           -0.415238       -0.164922      -0.051420  -0.458851   
emp.var.rate        1.000000        0.755155       0.195022   0.970308   
cons.price.idx      0.755155        1.000000       0.045835   0.657159   
cons.conf.idx       0.195022        0.045835       1.000000   0.276595   
euribor3m           0.970308        0.657159       0.276595   1.000000   
nr.employed         0.897173        0.472560       0.107054   0.942589   

                nr.employed  
Unnamed: 0         0.003782  
age               -0.041936  
duration          -0.044218  
campaign           0.161037  
pdays              0.381983  
previous          -0.514853  
emp.var.rate       0.897173  
cons.price.idx     0.472560  
cons.conf.idx      0.107054  
euribor3m          0.942589  
nr.employed        1.000000

#### Description

In [9]:
df.describe()

Unnamed: 0          age     duration     campaign        pdays  \
count  4119.000000  4119.000000  4119.000000  4119.000000  4119.000000   
mean   2059.000000    40.113620   256.788055     2.537266   960.422190   
std    1189.197208    10.313362   254.703736     2.568159   191.922786   
min       0.000000    18.000000     0.000000     1.000000     0.000000   
25%    1029.500000    32.000000   103.000000     1.000000   999.000000   
50%    2059.000000    38.000000   181.000000     2.000000   999.000000   
75%    3088.500000    47.000000   317.000000     3.000000   999.000000   
max    4118.000000    88.000000  3643.000000    35.000000   999.000000   

          previous  emp.var.rate  cons.price.idx  cons.conf.idx    euribor3m  \
count  4119.000000   4119.000000     4119.000000    4119.000000  4119.000000   
mean      0.190337      0.084972       93.579704     -40.499102     3.621356   
std       0.541788      1.563114        0.579349       4.594578     1.733591   
min       0.000000     -3.400000       92.201000     -50.800000     0.635000   
25%       0.000000     -1.800000       93.075000     -42.700000     1.334000   
50%       0.000000      1.100000       93.749000     -41.800000     4.857000   
75%       0.000000      1.400000       93.994000     -36.400000     4.961000   
max       6.000000      1.400000       94.767000     -26.900000     5.045000   

       nr.employed  
count  4119.000000  
mean   5166.481695  
std      73.667904  
min    4963.600000  
25%    5099.100000  
50%    5191.000000  
75%    5228.100000  
max    5228.100000

#### Unique Values

In [10]:
categorical_cols = df.select_dtypes(include='object').columns

for i in categorical_cols:
    print(f'{i}: {df[i].unique()}\n')

job: ['blue-collar' 'services' 'admin.' 'entrepreneur' 'self-employed'
 'technician' 'management' 'student' 'retired' 'housemaid' 'unemployed'
 'unknown']

marital: ['married' 'single' 'divorced' 'unknown']

education: ['basic.9y' 'high.school' 'university.degree' 'professional.course'
 'basic.6y' 'basic.4y' 'unknown' 'illiterate']

default: ['no' 'unknown' 'yes']

housing: ['yes' 'no' 'unknown']

loan: ['no' 'unknown' 'yes']

contact: ['cellular' 'telephone']

month: ['may' 'jun' 'nov' 'sep' 'jul' 'aug' 'mar' 'oct' 'apr' 'dec']

day_of_week: ['fri' 'wed' 'mon' 'thu' 'tue']

poutcome: ['nonexistent' 'failure' 'success']

y: ['no' 'yes']



In [11]:
numerical_cols = df.select_dtypes(include='number').columns

for i in numerical_cols:
    print(f'{i}: {df[i].unique()}\n')

Unnamed: 0: [   0    1    2 ... 4116 4117 4118]

age: [30 39 25 38 47 32 41 31 35 36 29 27 44 46 45 50 55 40 28 34 33 51 48 20
 76 56 24 58 60 37 52 42 49 54 59 57 43 53 75 82 71 21 22 23 26 81 61 67
 73 18 64 74 77 86 85 63 88 78 72 68 80 66 19 62 65 69 70]

duration: [ 487  346  227   17   58  128  290   44   68  170  301  148   97  211
  553  698  191   59   38  849  326  222  626  119  388  479  446  127
  109  113  393  151  256   42  525   57  499   84  137   31  430  126
  340  412  132   79  341  157  252  263  215   89  143   40   10  481
  233  204  403  180   16  447   81  361 1091  395  432  596   77  768
   96  357  459   11  264   93  374  158   95  835  505  300  390  274
  135  257  268  477   91   76  103  436  483  250  259  389    7  123
   92  297  406  104  854  147  203  149  144  394  523   73  197  108
   80  114  122 1161  181  239  360  314  984  663  141  706  797  311
   63  111   49  171  242  279  246  309  168  153  152   90  117  640
  199 1114   74  190

## Data Cleaning

#### Drop duration to avoid target leak

In [12]:
df.drop(columns=['duration', 'Unnamed: 0'], inplace=True)

#### Removing unknown values

In [13]:
columns = ['job', 'marital', 'education', 'default', 'housing', 'loan']

for col in columns:
    unique_vals = df[col].unique()
    unique_vals = [value for value in unique_vals if value != 'unknown']
    df[col] = df[col].apply(lambda x: np.random.choice(unique_vals) if x == 'unknown' else x)

#### Creating new 'previously_contacted' feature

In [14]:
df['previously_contacted'] = df['pdays'].map(lambda x: 0 if x == 999 else 1)

In [15]:
df.shape

(4119, 21)

In [16]:
df.head()

age          job  marital          education default housing loan  \
0   30  blue-collar  married           basic.9y      no     yes   no   
1   39     services   single        high.school      no      no   no   
2   25     services  married        high.school      no     yes   no   
3   38     services  married           basic.9y      no      no  yes   
4   47       admin.  married  university.degree      no     yes   no   

     contact month day_of_week  ...  pdays  previous     poutcome  \
0   cellular   may         fri  ...    999         0  nonexistent   
1  telephone   may         fri  ...    999         0  nonexistent   
2  telephone   jun         wed  ...    999         0  nonexistent   
3  telephone   jun         fri  ...    999         0  nonexistent   
4   cellular   nov         mon  ...    999         0  nonexistent   

  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  \
0         -1.8          92.893          -46.2      1.313       5099.1  no   
1          1.1          93.994          -36.4      4.855       5191.0  no   
2          1.4          94.465          -41.8      4.962       5228.1  no   
3          1.4          94.465          -41.8      4.959       5228.1  no   
4         -0.1          93.200          -42.0      4.191       5195.8  no   

  previously_contacted  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  

[5 rows x 21 columns]

In [17]:
df.to_csv('cleaned_bank.csv')

## Data Splitting

In [18]:
validation_df = df.sample(frac=0.2, random_state=0)
train_df = df.drop(validation_df.index)

In [19]:
train_df.shape, validation_df.shape

((3295, 21), (824, 21))

## Generating Tf Datasets

In [20]:
label_lookup = keras.layers.StringLookup(
    vocabulary=['no', 'yes'],
    num_oov_indices=0,
)

In [21]:
def encode_label(x, y):
    encoded_y = label_lookup(y)
    return x, encoded_y

def df_to_ds(df):
    df = df.copy()
    labels = df.pop('y')
    ds = tf.data.Dataset.from_tensor_slices((dict(df), labels))
    ds = ds.map(encode_label, num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.shuffle(buffer_size=len(df))
    return ds

In [22]:
train_ds = df_to_ds(train_df)
valid_ds = df_to_ds(validation_df)

#### Preview

In [23]:
for x, y in df_to_ds(train_df).take(1):
    print('Input: ', x)
    print()
    print('Target: ', y)

Input:  {'age': <tf.Tensor: shape=(), dtype=int64, numpy=37>, 'job': <tf.Tensor: shape=(), dtype=string, numpy=b'technician'>, 'marital': <tf.Tensor: shape=(), dtype=string, numpy=b'single'>, 'education': <tf.Tensor: shape=(), dtype=string, numpy=b'professional.course'>, 'default': <tf.Tensor: shape=(), dtype=string, numpy=b'no'>, 'housing': <tf.Tensor: shape=(), dtype=string, numpy=b'no'>, 'loan': <tf.Tensor: shape=(), dtype=string, numpy=b'yes'>, 'contact': <tf.Tensor: shape=(), dtype=string, numpy=b'telephone'>, 'month': <tf.Tensor: shape=(), dtype=string, numpy=b'jun'>, 'day_of_week': <tf.Tensor: shape=(), dtype=string, numpy=b'mon'>, 'campaign': <tf.Tensor: shape=(), dtype=int64, numpy=4>, 'pdays': <tf.Tensor: shape=(), dtype=int64, numpy=999>, 'previous': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'poutcome': <tf.Tensor: shape=(), dtype=string, numpy=b'nonexistent'>, 'emp.var.rate': <tf.Tensor: shape=(), dtype=float64, numpy=1.4>, 'cons.price.idx': <tf.Tensor: shape=(), dtype=f

## Feature Space

#### Removing labels

In [24]:
train_ds_with_no_labels = train_ds.map(lambda x, _: x)

#### Configuring FeatureSpace

In [25]:
feature_space = FeatureSpace(
    features={
        # categorical features encoded as integers
        'previously_contacted': FeatureSpace.integer_categorical(num_oov_indices=0),
        
        # categorical features encoded as string
        'marital': FeatureSpace.string_categorical(num_oov_indices=0),
        'education': FeatureSpace.string_categorical(num_oov_indices=0),
        'default': FeatureSpace.string_categorical(num_oov_indices=0),
        'housing': FeatureSpace.string_categorical(num_oov_indices=0),
        'loan': FeatureSpace.string_categorical(num_oov_indices=0),
        'contact': FeatureSpace.string_categorical(num_oov_indices=0),
        'month': FeatureSpace.string_categorical(num_oov_indices=0),
        'day_of_week': FeatureSpace.string_categorical(num_oov_indices=0),
        'poutcome': FeatureSpace.string_categorical(num_oov_indices=0),

        # categorical features to hash and bin
        'job': FeatureSpace.string_hashed(num_bins=3),

        # Numerical features to hash and bin
        'pdays': FeatureSpace.integer_hashed(num_bins=4),

        # Numerical features to normalize and bin
        'age': FeatureSpace.float_discretized(num_bins=4),

        # Numerical features to normalize
        'campaign': FeatureSpace.float_normalized(),
        'previous': FeatureSpace.float_normalized(),
        'emp.var.rate': FeatureSpace.float_normalized(),
        'cons.price.idx': FeatureSpace.float_normalized(),
        'cons.conf.idx': FeatureSpace.float_normalized(),
        'euribor3m': FeatureSpace.float_normalized(),
        'nr.employed': FeatureSpace.float_normalized()
    },

    crosses=[
        FeatureSpace.cross(feature_names=('age', 'job'), crossing_dim=8),
        FeatureSpace.cross(feature_names=('housing', 'loan'), crossing_dim=6),
        FeatureSpace.cross(
            feature_names=('poutcome', 'previously_contacted'), crossing_dim=2
        ),
    ],
    output_mode='concat',
)

#### Batching

In [26]:
train_ds = train_ds.batch(32)
valid_ds = valid_ds.batch(32)

#### Adapt the FeatureSpace

In [27]:
feature_space.adapt(train_ds_with_no_labels)

## Data Preprocessing

In [28]:
preprocessed_train_ds = train_ds.map(
    lambda x, y: (feature_space(x), y), num_parallel_calls=tf.data.AUTOTUNE
).prefetch(tf.data.AUTOTUNE)

preprocessed_valid_ds = valid_ds.map(
    lambda x, y: (feature_space(x), y), num_parallel_calls=tf.data.AUTOTUNE
).prefetch(tf.data.AUTOTUNE)

## Model Building

#### Raw and Encoded Features

In [29]:
dict_inputs = feature_space.get_inputs()
encoded_features = feature_space.get_encoded_features()

#### Layers

In [30]:
x = keras.layers.Dense(64, activation='relu')(encoded_features)
x = keras.layers.Dropout(0.5)(x)
output = keras.layers.Dense(1, activation='sigmoid')(x)

#### Model Compilation

In [31]:
model = keras.Model(inputs=encoded_features, outputs=output)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

#### Fitting

In [32]:
model.fit(
    preprocessed_train_ds,
    validation_data=preprocessed_valid_ds,
    epochs=20,
    verbose=2
)

Epoch 1/20
103/103 - 2s - 16ms/step - accuracy: 0.8634 - loss: 0.3673 - val_accuracy: 0.9029 - val_loss: 0.2742
Epoch 2/20
103/103 - 1s - 6ms/step - accuracy: 0.8968 - loss: 0.2974 - val_accuracy: 0.9090 - val_loss: 0.2651
Epoch 3/20
103/103 - 1s - 6ms/step - accuracy: 0.9002 - loss: 0.2976 - val_accuracy: 0.9090 - val_loss: 0.2645
Epoch 4/20
103/103 - 1s - 6ms/step - accuracy: 0.8944 - loss: 0.2949 - val_accuracy: 0.9114 - val_loss: 0.2627
Epoch 5/20
103/103 - 1s - 6ms/step - accuracy: 0.9008 - loss: 0.2890 - val_accuracy: 0.9090 - val_loss: 0.2633
Epoch 6/20
103/103 - 1s - 6ms/step - accuracy: 0.8980 - loss: 0.2879 - val_accuracy: 0.9090 - val_loss: 0.2631
Epoch 7/20
103/103 - 1s - 6ms/step - accuracy: 0.9011 - loss: 0.2810 - val_accuracy: 0.9114 - val_loss: 0.2636
Epoch 8/20
103/103 - 1s - 6ms/step - accuracy: 0.8986 - loss: 0.2803 - val_accuracy: 0.9066 - val_loss: 0.2685
Epoch 9/20
103/103 - 1s - 6ms/step - accuracy: 0.9020 - loss: 0.2783 - val_accuracy: 0.9078 - val_loss: 0.2664


#### Inference Model

In [33]:
inference_model = keras.Model(inputs=dict_inputs, outputs=output)

#### Save the model

In [34]:
inference_model.save('inference_model.keras')

## Prediction

In [35]:
sample = {
    "age": 30,
    "job": "blue-collar",
    "marital": "married",
    "education": "basic.9y",
    "default": "no",
    "housing": "yes",
    "loan": "no",
    "contact": "cellular",
    "month": "may",
    "day_of_week": "fri",
    "campaign": 2,
    "pdays": 999,
    "previous": 0,
    "poutcome": "nonexistent",
    "emp.var.rate": -1.8,
    "cons.price.idx": 92.893,
    "cons.conf.idx": -46.2,
    "euribor3m": 1.313,
    "nr.employed": 5099.1,
    "previously_contacted": 0,
}

input_dict = {
    name: keras.ops.convert_to_tensor([value]) for name, value in sample.items()
}
predictions = inference_model.predict(input_dict)

print(
    f"This particular client has a {100 * predictions[0][0]:.2f}% probability "
    "of subscribing a term deposit, as evaluated by our model."
)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 367ms/step
This particular client has a 8.39% probability of subscribing a term deposit, as evaluated by our model.
